import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";
import RefreshTokenProvider from "@/components/AuthHook";
import Navbar from "@/components/Navbar";
import NavbarWrapper from "@/components/NavbarWrapper";
import ThemeProvider from "@/components/ThemeProvider";
import { Footer } from "@/components/Footer";
import Script from "next/script";
import { GA_MEASUREMENT_ID } from "@/lib/gtag";

export const metadata = {
  title: "Tutelage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="mt-0 pt-0">
      <head>
        <link
          rel="icon"
          href="/only-logo-black-border-yellow-bg.svg"
          type="image/svg+xml"
        />
      </head>
      <body className="relative">
        {/* Google Analytics */}
        {GA_MEASUREMENT_ID && (
          <>
            <Script
              strategy="afterInteractive"
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
            />
            <Script
              id="google-analytics"
              strategy="afterInteractive"
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${GA_MEASUREMENT_ID}', {
                    page_path: window.location.pathname,
                  });
                `,
              }}
            />
          </>
        )}
        <ThemeProvider>
          <RefreshTokenProvider>
            <AuthProvider>
              <NavbarWrapper>
                  <Navbar />
              </NavbarWrapper>
              <div className="relative z-10">{children}</div>
              <Footer />
              <Toaster />
            </AuthProvider>
          </RefreshTokenProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
