import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";
import RefreshTokenProvider from "@/components/AuthHook";
import Navbar from "@/components/Navbar";
import NavbarWrapper from "@/components/NavbarWrapper";
import ThemeProvider from "@/components/ThemeProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <RefreshTokenProvider>
            <AuthProvider>
              <NavbarWrapper>
                <Navbar />
              </NavbarWrapper>
              {children}
              <Toaster />
            </AuthProvider>
          </RefreshTokenProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
